# run with: wandb sweep config/sweeps/contrastive_superfamily_sweep.yaml
# wandb agent <SWEEP_ID>
program: contrasted/train.py
method: bayes
project: CATHe-Contrastive-Hierarchical
name: Superfamily_Temp_LR_Proj_Sweep
metric:
  name: val/centroid_f1_macro
  goal: maximize

# Hyperparameters to search
parameters:
  model.temperature:
    distribution: uniform
    min: 0.01
    max: 0.5

  model.learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3

  model.output_dim:
    values: [128, 256, 512]

  model.enable_visualization:
    value: false

# Command to launch training at level 3 only
command:
  - ${env}
  - bash
  - -lc
  - "TMPDIR=/tmp python ${program} training.cath_levels=[3] ${args_no_hyphens}" 