program: src/train.py
method: bayes
project: CATHe
name: ESMC_sweep
metric:
  goal: maximize
  name: val/balanced_acc

parameters:
  model.learning_rate:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  model.weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.001
  model.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  
  # For Hydra, we need to use the special +group=value syntax
  # Note the + prefix which is required for Hydra overrides
  +data:
    value: esmc

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens} 