program: src/train.py
method: bayes
project: CATHe
name: ProtT5_sweep
metric:
  goal: maximize
  name: val/balanced_acc

parameters:
  model.learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  model.weight_decay:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3
  model.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5


command:
  - ${env}
  - python
  - ${program}
  - "data=prot_t5"
  - ${args_no_hyphens}