program: src/train.py
method: bayes
metric:
  goal: maximize
  name: val/balanced_acc

# Parameters to optimize (with their search spaces)
parameters:
  # Model parameters
  model.learning_rate:
    distribution: log_uniform_values  # Changed from log_uniform
    min: 0.00001
    max: 0.001
  model.weight_decay:
    distribution: log_uniform_values  # Changed from log_uniform
    min: 0.000001
    max: 0.0001
  model.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  model.hidden_sizes.0:
    values: [512, 768, 1024, 2048]
  model.hidden_sizes.1:
    values: [512, 768, 1024, 2048]
  
  # Training parameters
  training.batch_size:
    values: [128, 256, 512] 

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}