data:
  data_dir: "data"
  train_embeddings: "embeddings/SF_Train_ProtT5.npz"
  val_embeddings: "embeddings/SF_Val_ProtT5.npz"
  test_embeddings: "embeddings/SF_Test_ProtT5.npz"
  train_labels: "annotations/Y_Train_SF.csv"
  val_labels: "annotations/Y_Val_SF.csv"
  test_labels: "annotations/Y_Test_SF.csv"

model:
  embedding_dim: 1024
  hidden_sizes: [128, 128, 128]
  dropout: 0.5
  use_batch_norm: true
  l1_reg: 1e-5
  l2_reg: 1e-4

training:
  # Basic training parameters
  batch_size: 256
  learning_rate: 1e-5
  max_epochs: 200
  early_stopping_patience: 30
  
  # Hardware configuration
  gpus: 1
  num_workers: 4
  
  # Advanced training options
  seed: 42
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  precision: 32
  
  # Logging and checkpointing
  log_every_n_steps: 50
  save_top_k: 3
  monitor_metric: "val_accuracy"
  monitor_mode: "max" 