data:
  data_dir: "data"
  train_embeddings: "embeddings/SF_Train_ProtT5.npz"
  val_embeddings: "embeddings/SF_Val_ProtT5.npz"
  test_embeddings: "embeddings/SF_Test_ProtT5.npz"
  train_labels: "annotations/Y_Train_SF.csv"
  val_labels: "annotations/Y_Val_SF.csv"
  test_labels: "annotations/Y_Test_SF.csv"

model:
  embedding_dim: 1024
  hidden_sizes: [128, 128, 128]
  dropout: 0.5
  learning_rate: 1e-4

training:
  # Basic training parameters
  batch_size: 256
  max_epochs: 200
  early_stopping_patience: 30
  
  # Hardware configuration
  num_workers: 4
  
  # Advanced training options
  seed: 42
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  precision: "16-mixed"
  
  # Logging and checkpointing
  log_every_n_steps: 50
  save_top_k: 3
  monitor_metric: "val_acc"
  monitor_mode: "max"
  
  # Output paths
  output_dir: "outputs"
  checkpoint_dir: "${training.output_dir}/checkpoints"
  log_dir: "${training.output_dir}/logs" 