data:
  data_dir: "data"
  train_embeddings: "embeddings/SF_Train_ProtT5.npz"
  val_embeddings: "embeddings/SF_Val_ProtT5.npz"
  test_embeddings: "embeddings/SF_Test_ProtT5.npz"
  train_labels: "annotations/Y_Train_SF.csv"
  val_labels: "annotations/Y_Val_SF.csv"
  test_labels: "annotations/Y_Test_SF.csv"

model:
  # Core architecture parameters
  embedding_dim: 1024
  hidden_sizes: [512, 256, 128]
  dropout: 0.3
  
  # Optimization parameters
  learning_rate: 5e-5
  weight_decay: 0.01
  scheduler_factor: 0.2
  scheduler_patience: 7
  focal_gamma: 2.0

training:
  # Basic training parameters
  batch_size: 128
  max_epochs: 300
  early_stopping_patience: 15
  
  # Hardware configuration
  num_workers: 4
  
  # Advanced training options
  seed: 42
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  precision: "16-mixed"
  
  # Logging and checkpointing
  log_every_n_steps: 50
  monitor_metric: "val_balanced_acc"
  monitor_mode: "max"
  
  # Output paths
  output_dir: "outputs"
  checkpoint_dir: "${training.output_dir}/checkpoints"
  log_dir: "${training.output_dir}/logs" 