defaults:
  - _self_
  - data: protT5

model:
  # Architecture
  embedding_dim: ${data.embedding_dim}
  projection_dims: [1024, 512]
  output_dim: 128
  dropout: 0.3
  # Optimization
  learning_rate: 1e-4
  weight_decay: 1e-4
  temperature: 0.07
  # --- Added Visualization ---
  visualization_method: "tsne" # "umap" or "tsne"
  enable_visualization: false
  tsne_viz_dir: "results/tsne_plots"
  umap_viz_dir: "results/umap_plots"

training:
  # Training parameters
  batch_size: 1024
  max_epochs: 100
  accumulate_grad_batches: 1
  cath_levels: [3] # <--- (0=C, 1=A, 2=T, 3=H)

  # Monitoring
  monitor_metric: "val/centroid_f1_macro"
  monitor_mode: "max"
  early_stopping_patience: 10
  log_every_n_steps: 100

  # Hardware configuration
  num_workers: 16
  accelerator:
    float32_matmul_precision: "high"
    devices: 1

  # Training options
  seed: 42
  gradient_clip_val: 1.0
  precision: "16-mixed"

  # Output paths - These will be dynamically modified per level
  output_dir: "outputs_contrastive_hierarchical" # Base output directory