input: data/CATH/clustered_datasets_0.05/unified_train_set/train.fasta # the input sequences we wish to make our database from
model_path: overlap_loss_ckpts/epoch=149-step=1463550.ckpt # the model we want to use to embed our sequences
index_path: data/CATH/vector_index # the path we want to save our vector index to
ids: # if we only want to build our index from a subset of input [OPTIONAL]
device: 'cpu'