wandb: true
project_name: hifinn
batch_size: 8
train_ids_path: 'data/CATH/clustered_datasets_0.05/unified_train_set/train.fasta'
test_ids_path: 'data/CATH/clustered_datasets_0.05/s90/test.fasta'
val_ids_path: 'data/CATH/clustered_datasets_0.05/unified_val_set/valid.fasta'
embeddings_path: 'data/CATH/esm2_embeddings_layer32'
annotations: 'data/CATH/cath_id_to_sf.json'
epochs: 250
save_path: './overlap_loss_ckpts/'
num_workers: 60
checkpoint_path: ''
margin_loss: 
  margins: 
    - 1
    - 0.9
    - 0.8
    - 0.7
  metric: 'cosine'
optimiser:
  weight_decay: 0.1
  lr: 0.0001 
  max_lr: 0.01
  min_lr: 0.00005 
  num_warmup_epochs: 1
  gradient_clip_val: 0.1
  eps: 1e-08
  betas:
    - 0.9
    - 0.999
normalize: True
dropout: 0.00
weights: 
  - 1
  - 0.9
  - 0.8
  - 0.7
model:
  hidden_size_1: 1024
  output_size: 512
train_on_classes: false
devices:
  - 0
precision: '16-mixed'
strategy: 'ddp'